### ISSUE TITLE
Suggestion: Growth Times

### ISSUE THREAD

**Issue by 2lstgun** [Asthereon/green-thumb#3]
A simple suggestion for the addition of average growth time for each seed.

**Comment by Asthereon** [comment]
Big fan of this idea, I'll add this to my to-do list!

**Comment by Asthereon** [comment]
I have created a Pull Request for this feature to be merged into RuneLite.

Its status can be monitored here: https://github.com/runelite/plugin-hub/pull/2128

I will close this issue once it is successfully merged in.

**Comment by Asthereon** [comment]
The update including this feature has been merged into RuneLite, thank you for the suggestion!
