### ISSUE TITLE
Plugin currently unavailable - Runelite change causes plugin build to fail

### ISSUE THREAD

**Issue by robmonte** [Asthereon/green-thumb#4]
The plugin is currently unavailable to due a Runelite change which causes the plugin to fail to build.

**Comment by Asthereon** [comment]
I will investigate this today.

**Comment by Asthereon** [comment]
I've tracked down the issue, and will release a patch for this later today alongside a new feature.

**Comment by Asthereon** [comment]
I have created a Pull Request for this fix to be merged into RuneLite.

Its status can be monitored here: [runelite/plugin-hub#2202](https://github.com/runelite/plugin-hub/pull/2202)

I will close this issue once it is successfully merged in.

**Comment by Asthereon** [comment]
The update including this fix has been merged into RuneLite, thank you for the bug report!
