### ISSUE TITLE
[Request] Add seed info tooltip to seed vault

### ISSUE THREAD

**Issue by 0anth** [Asthereon/green-thumb#5]
Currently the seed info tooltip doesn't appear when hovering over seeds in the seed vault.

It would be super useful to be able to see this directly from the seed vault, without having to take the seeds out first.

![Screenshot 2022-01-02 172346](https://user-images.githubusercontent.com/1083462/147871674-7c8dc427-8756-4a3b-b7e5-8457585cafaa.jpg)

**Comment by Asthereon** [comment]
This is a great suggestion I hadn't even thought about, I'll add this to my to-do list!

**Comment by Asthereon** [comment]
I have created a Pull Request for this feature to be merged into RuneLite.

Its status can be monitored here: https://github.com/runelite/plugin-hub/pull/2255

I will close this issue once it is successfully merged in.

**Comment by Asthereon** [comment]
The update including this feature has been merged into RuneLite, thank you for the suggestion!
