### ISSUE TITLE
Add an indicator when magic secateurs are in inventory but not equipped

### ISSUE THREAD

**Issue by Asthereon** [Asthereon/green-thumb#7]
This would help prevent doing herb runs with magic secateurs in the inventory and missing out on the bonus.

**Comment by sybren9** [comment]
https://github.com/Ryanbarker0/magic-secateurs

**Comment by Asthereon** [comment]
Update that made magic secateurs work from the inventory makes this obsolete.

[15 February](https://oldschool.runescape.wiki/w/15_February) [2023](https://oldschool.runescape.wiki/w/2023)
